### ISSUE TITLE
Updated data for 3.20 or at least 3.19?

### ISSUE THREAD

**Issue by xophermmanuel** [Valalol/Star-Citizen-Navigation#15]
**Is your feature request related to a problem? Please describe.**
The problem is the data is based on outdated location database.

**Describe the solution you'd like**
How do we get and update it ourselves?

**Comment by Valalol** [comment]
Sorry for the lack of updates, I've been away from the game for quite some time.
If you want do update the dabase yourself, you can modify database.json file and get some more up to date informations
