### ISSUE TITLE
Need More Detailed Instructions

### ISSUE THREAD

**Issue by Kyle-97** [Valalol/Star-Citizen-Navigation#4]
Cannot get app to run... need more info on how to install.

**Comment by Valalol** [comment]
Hey, Have you downloaded the app from the release tab on github ?
If so, put the zip file in a convenient place and unzip it
In the folder, there should be a readme and two other folders one for the tools and one for the script
Try to read and follow the readme (install python etc)
And then, start the file named `star-citizen-navigation-tool.exe` in the `star-citizen-navigation-tool-win32-x64` folder
If everything worked, the app should start and prompt you with a few windows
