### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Dunravin** [Valalol/Star-Citizen-Navigation#6]
Installed python 3.10.4 and added to PATH during install.
ran pip install pyperclip==1.8.2 in a dos box

Navtool is extracted in my downloads folder on C:

SC is installed on another drive

With SC running started the tool and selected Hurston cave s21

ran the chat command /showlocation

nothing happens in the tool. All coords etc all zero.

Which version of python do you recommend?

**Comment by Valalol** [comment]
Hey Dunravin, 
I'm currently using Python 3.9.6 but that shouldn't be a problem.
Two things, is the small light at the bottom of the UI still Green, and is there anything being copied in your clipboard when you type the command in the game chat ?
Greetings,
Valalol

**Comment by Dunravin** [comment]
Hi Valalol

Yes I have a green light.
I'm not sure anything is being copied to the clipboard. I haven't tried pasting clipboard into an editor after running the chat command. I'll try that later and report back.

My windows 10 install has clipboard history turned off for security but the clipboard does work for general use.

Thanks for the quick reply :D

**Comment by Valalol** [comment]
No problem.
Yeah, the only thing my script sees is the clipboard. 
So if nothing gets copied, then I can't really do anything for you :/

**Comment by Dunravin** [comment]
Ok just testing. Nothing is being copied to the clipboard by SC

Any ideas on why or things to check?

**Comment by Valalol** [comment]
Are you typing `\showlocation` in the game chat ? Like the global chat ?

**Comment by Dunravin** [comment]
typing /showlocation in global. Nothing outputted into chat.
Emotes like /chicken work fine

**Comment by Dunravin** [comment]
So according to some twitch viewers the /showlocation command may of been removed but for some people it still works. I'm guessing this could be related to when star citizen was installed. I did a clean install a few months ago but if you've had installed for a long time and just upgraded over time it may still be working. Can't find any documentation from RSI, nothing in patch notes going back to 3.14

**Comment by Valalol** [comment]
Yeah, we had some people for whom the command wasn't copying any coordinates and we have an issue on the issue council for this. 
Here is the link : [https://issue-council.robertsspaceindustries.com/projects/STAR-CITIZEN/issues/STARC-5660](https://issue-council.robertsspaceindustries.com/projects/STAR-CITIZEN/issues/STARC-5660)
I really doubt that it could have been removed from the game and my game isn't really old, I do a clean reinstall from time to time.
