### ISSUE TITLE
Error at launch

### ISSUE THREAD

**Issue by Mikeleid** [Valalol/Star-Citizen-Navigation#7]
box show saying ModuleNotFoundError: No Module Named ' request '

**Comment by Valalol** [comment]
Hey Mikeleid,
Try to re-download the package and run the `install.bat` I changed a small thing to install this library too
or do `pip install request` in a command prompt
Hope that helps you :)
Valalol

**Comment by Mikeleid** [comment]
try the install.bat i had the old pip version i update it and still same message :(

**Comment by Valalol** [comment]
Have you tried to do the `pip install request` in a command prompt ?

**Comment by Mikeleid** [comment]
yes i did it how it update my installed version of PiP to the leatest one i re try the install and it say all dependency installed

**Comment by Mikeleid** [comment]
i have re download the who;e zip and re did install.bat it download 4 more item and now it work correctly tks

**Comment by Valalol** [comment]
Nice have fun !
